baseurl = "/"
title = "stealthtaco"
copyright = "Copyright (c) 2021, all rights reserved."
canonifyurls = true
languageCode = "en-US"
paginate = 3
theme = "hugo-dusk"
publishDir = "docs"

googleAnalytics = ""
disqusShortname = ""

[author]
  name = "stealthtaco"

SectionPagesMenu = "main"

# Configure syntax highlight
[markup]
  [markup.highlight]
    style = "rrt" # dark themes: monokai, api, fruity, native, rrt, swapoff

#[[menu.main]]
#  name = "Posts"
#  weight = -120
#  identifier = "posts"
#  url = "/posts/"

[[menu.main]]
  name = "Tags"
  weight = -110
  identifier = "tag"
  url = "/tags/"

[params.meta]
  keywords = "blog, tech"
  description = "Personal blog."

[params]
  github = "thestealthtaco"
  #gitlab = "gitlab id"
  twitter = "thestealthtaco"
  #linkedin = "linkedin id"
  #email = "myemail"
  theme_colors = "default-dark" # uses color css file under static/css/default-dark.css
  #utterancesRepo="REPO_NAME" # Utterances is enabled when this param is set
  #utterancesTheme="github-dark" # Default: github-dark
  #utterancesIssueTerm="pathname" # Default: pathname
